### ISSUE TITLE
multiple institutions with same name fails quietly

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus#1204]
Consider the following case:

- two regions named R_A and R_B
- R_A has a DeployInst named Inst
- R_B has a NullInst named Inst
- each institution has initial facilities
- the DeployInst deploys facilities at some frequency

If both institutions have the same name, no deployment will occur.

My guess is that the nullinst prototype is overwriting the deployinst in the context's protos_ mapping.

**Comment by rwcarlsen** [comment]
The actual behavior is that one prototype overwrites another with the same name - last one wins.  This behavior is intentional - allowing the prototype for a particular name/identifier be changed/modified.  However, I can see accidental prototype name duplication occuring.  I think we can safely assume that nobody intends to have duplicate prototype names come from a single input file though.  So maybe we can make the check occur during input file reading rather than when the prototype is added to the context.
