### ISSUE TITLE
Store inventories at run time

### ISSUE THREAD

**Issue by scopatz** [cyclus/cyclus#1223]
see https://groups.google.com/d/topic/cyclus-dev/RxiOb3jUSbM/discussion

**Comment by rwcarlsen** [comment]
I would recommend a new canonical kernel table of the following schema: ``Time, AgentId, NucId, Quantity``.  Reasoning to do this includes:

* Allows the data to be stored in a standard way that analysis tools/workflows can use without requiring special knowledge of the db backends and without binding directly to libcyclus.

* Cyclist can use/benefit from this table.  Otherwise, either binding to libcyclus will be required or complex deserialization code will need to be written in java.  Niether of which are likely to happen anywhere in the near/medium term future IMO.  This argument applies to Cyan also.  Also, the binding approach will require cyclus to be installed locally in order to use - making remote-execution-only-users unable to use this new inventory data.

* Sqlite backend will be *very slow* using the dump ``map<int,double>`` approach because it uses boost serialization for containers (including arbitrary nesting) - which uses xml.  And this data format, in addition to being surly different from how HDF5 will store the data, will be extremely unpleasant to work with - likely deterring any would-be analyists/analylsis tool builders.

The main alternative of dumping the the ``map<int,double>`` directly into the backends is also negligibly different in difficulty of implementation.  Both ways are easy to implement.

A warning/note for the future implementor:

```
!!! Be careful not to modify the materials retrieved from agents' SnapshotInv functions !!!
```

**Comment by scopatz** [comment]
For n nuclides, the `Time, AgentId, NucId, Quantity`  strategy is at least 28*(n-1) bytes larger than the `map<int, double>` method because of the SimId (20 b), Time (4 b), and AgentId (4 b) being unnecessarily repeated. This is excessive for even 100s of nuclides, let alone 1000s. I believe that the type system is there to be used.

**Comment by scopatz** [comment]
So back of the envelope: 28 b/nuc * 100 nuclide * 100 facilities * 1200 time steps / (1024*1024) is 320 Mb that is duplicated information.  Go up to 300 nuclides and you basically have an extra gig just in metadata.

**Comment by rwcarlsen** [comment]
The AgendId  must be stored even for the map<int,double> only method.  So
that is 24 b wasted vs 12 b required as opposed to 0 b wasted and 12 b
required.  The space penalty for the schema I suggested is a constant
multiple on the size that would be required.  So 3 GB table my schema
becomes 1 GB table your method.  The penalty is always really close to 3X -
regardless of how many facilities/nuclides (except for really small db's) -
it never gets bigger.  I don't think the difference between those two sizes
is worth the disbenefits I outlined.

**Comment by scopatz** [comment]
I think that there is a misunderstanding. For a single agent, for a single time, the method I am championing takes 1 row which happens to be size 28 (SimId, Time, AgentId) + 12*n (Nuc + Value).

Your proposed method takes n rows, each of which is sized 40. This yeilds a total size of 40*n.

The difference in size is thus (40 - 12)*n - 28 = 28(n-1).  This is significant as it could easily mean the difference between being able to load the whole table in memory, or not.  Also the I/O time on such a large amount of data should not be discounted either.

Frankly, since this is optional, I wouldn't mind if the table schema where also part of what is set in the input file as long as my proposal is ultimately implemented.

**Comment by rwcarlsen** [comment]
I don't think I misunderstand.  For a single agent, single time:

* scopatz schema: 12*n
* rwcarlsen schema: (12+20+4+4)*n

12n vs 40n ==> rwcarlsen/scopatz == 40/12 ~= 3X as large.

Since it is easy enough to implement both, I'd vote for a separate toggle
to turn each on/off so users can have one, the other, both, or none.

**Comment by scopatz** [comment]
> Since it is easy enough to implement both, I'd vote for a separate toggle to turn each on/off so users can have one, the other, both, or none.

Works for me.
