### ISSUE TITLE
install.py cyclus version detection

### ISSUE THREAD

**Issue by bam241** [cyclus/cyclus#1369]
cyclus version detection relies on git tag.
this is then failing when using the tarball version.

seems users need to specify it manually.

Shall we update `master` ( and the tarball) with a default value ?

**Comment by scopatz** [comment]
I don't think that we should.  I think it is better for users to specify this manually.  Also note that this is an issue when you use cmake directly, not just from install.py

**Comment by bam241** [comment]
when using python install.py (in a fresh docker container)
```
-- NUMPY_VERSION_STRING = 1.11.0
fatal: Not a git repository (or any of the parent directories): .git
CMake Warning at CMakeLists.txt:323 (MESSAGE):
  Unable to read current core version, falling back to previous version.
  Core version will be set to -1


-- core version ($CYCLUS_CORE_VERSION) set to: -1
-- Found '/root/cyclus-1.5.0/share/cyclus_nuc_data.h5'
Traceback (most recent call last):
  File "/root/cyclus-1.5.0/src/hdf5_back_gen.py", line 358, in <module>
    DB_TO_VL[db] = row[8]
IndexError: tuple index out of range
CMake Error at src/CMakeLists.txt:29 (message):
  Process hdf5_back_gen.py 'QUERY' failed, result = '1'


-- Configuring incomplete, errors occurred!
See also "/root/cyclus-1.5.0/build/CMakeFiles/CMakeOutput.log".
See also "/root/cyclus-1.5.0/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "install.py", line 208, in <module>
    main()
  File "install.py", line 205, in main
    install_cyclus(args)
  File "install.py", line 92, in install_cyclus
    shell=(os.name == 'nt'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'cmake', '/root/cyclus-1.5.0', u'-DCMAKE_INSTALL_PREFIX=/root/.local', u'-DDEFAULT_ALLOW_MILPS=TRUE']' returned non-zero exit status 1
```

**Comment by katyhuff** [comment]
I kindof do think we should give a version for the tarball. We only make one tarball per core version of cyclus, and every single build (from the tarball) will require --core-version=1.5.0 . So, we basically have three options:

1) Fix the installation instructions for the tarball build to include the --core-version=1.5.0 flag in the install
2) Make 1.5.0 the default in the tarball
3) When it fails to find the version via the git tag, have CMake look for the version in release/symbols.json (which currently includes the following version text):
```
./release/symbols.json:  "version": "Cyclus Core 1.5.0 (1.5.0-rc1-3-g55a30b2)",
./release/symbols.json:  "tag": "1.5.0",
```

Thoughts on a preference? I'm cc'ing undergraduate researcher @skc222 , who is interested in helping submit a fix to this bug.

**Comment by scopatz** [comment]
If we really want the version in the tarball the fix is to have a file checked into the repo that contains the version number (x.y.z).  Then if CMake detects fails to detect a git version and it wasn't specified on the command line or in the environment, it will use the one in this file. This is basically @katyhuff's option (3), but I would recommend against using symbols.json, since it is basically deprecated.

**Comment by katyhuff** [comment]
> it is basically deprecated. 
In what sense, @scopatz ?

**Comment by scopatz** [comment]
symbols.json was used for the ABI stability test, which we have turned off to get CI to pass because ABI compatibility was broken a few times.  Though this is a little off topic, I am in favor removing those tests and files. They didn't help as much as I thought they would.

**Comment by katyhuff** [comment]
So, @skc222 has created a nice little python file that can currently pull the version number from the symbols.json file.

Perhaps we should use that until symbols.json is actually removed from the repository. If symbols.json is removed from the repository, then at that point it would be appropriate to replace it with a single-purpose file with the version number. Creating that single purpose file now adds unnecessary cruft, in my opinion, since the symbols.json file already contains that info.


As an alternative, of course, perhaps robust to any of these concerns, we could just go with option 1, adding a hint in the install docs for the tarball installation. That hint could/should go here: https://github.com/cyclus/cyclus.github.com/blob/source/source/user/install_from_tarball.rst#compiling-cyclus

It can be just adding a simple sentence like so:

```rst
If you were successful then Cyclus has been installed and you can skip down to Installing Cycamore!
If you received an error message concerning the Cyclus Core Version, please use `python install.py --core-version=1.5.0`. 
```

Preferences?

**Comment by scopatz** [comment]
Maybe @skc222 can just remove symbols.json and the related tests as part of this?  Alternatively, I am happy to remove it myself.

**Comment by skc222** [comment]
Yes sure @scopatz but then are you suggesting to use option 1 suggested above by @katyhuff to resolve this issue? If yes then I can work on improving documentation accordingly.

**Comment by scopatz** [comment]
@skc222 I am strongly recommending that if option 3 is pursued, symbols.json is not used for an activity beyond which it is designed. If this means removing symbols.json and the related tests, I am happy with that state of affairs. I am also happy if all of the symbols stuff is ignored wrt to this issue.

**Comment by katyhuff** [comment]
I've created a new issue related to deprecating the ABI tests (#1380). @skc222 will make the documentation change to solve the tarball situation relevant to this issue. The ABI tests and peripherals like symbols.json can be removed by whomever has time for issue #1380 first!

**Comment by scopatz** [comment]
Thanks @katyhuff

**Comment by skc222** [comment]
Can we close this issue?

**Comment by scopatz** [comment]
I am happy with closing it, but we should probably ask @bam241

**Comment by scopatz** [comment]
since @katyhuff opened the deprecation one.

**Comment by bam241** [comment]
I thing, we are good!
thanks you guys !
