### ISSUE TITLE
any attempt to run cyclus via python ends in segfault

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclus#1589]
In the updated build under development in #1588, most of the tests pass.  The only one that does not attempts to call `cyclus` via the python `cyclus.main.main()` method in `test_main.py`.

I've replicated the behavior by just invoking:
```
from cyclus.main import main

main()
```
It appears to segfault as the program attempts to shutdown, having completed any actual computing.  It may be related to unloading the dynamically loaded modules? (hope that's not a red herring)

Tracking this down will requires a deep dive into a few layers of python/C++ interface. 

See also #1512, #1535, and #1543

**Comment by bennibbelink** [comment]
Been playing around with this in gdb.  The segfaults occur when unloading the dynamically loaded modules, but based based on the backtrace I think they may be due to invalid references to cyclib in pymodule.pyx (cyclib doesn't exist in the module ?)

Will do some more digging... its taking time to understand how the python wrappers interact with the C++

**Comment by gonuke** [comment]
Thanks for the update.  This sounds like something that is hard to find but might have a quick fix once you do (🤞)

**Comment by bennibbelink** [comment]
UPDATE: I found **a** fix in the dummy project, I will try to implement it in cyclus now.  I don't think that it is the best practice but it is working in the simple case.

Essentially what I've done is build each cython module in `src/` as its own shared library, then in `__init__.py` I import it (instead of calling `cyclus.lib.py_import_call_init`, it is this broken functionality in `pyhooks.cc` that I think should be the "correct" fix)

**Comment by bennibbelink** [comment]
I found a different fix in the dummy repo which I think is "more correct" (commit [0729d6f](https://github.com/bennibbelink/cython-playground/commit/0729d6f972a7a6e29e41c6c2f44f79bab9310c1a)).

This is what (I think) is happening in cyclus:
### When run using the cli
- `PyStart()` is called appropriately (in `pyhooks.cc`)
- The cython modules are appended to the initialization table as built-in python modules
- Python is initialized
- the cython modules are imported, and everything works well
### When run from Python
- `PyImportCallInit()` is called in `__init__.py` which initializes the cython modules
- `PyStart()` is called appropriately from within `libcyclus`
- The cython modules are appended to the initialization table but since the python interpreter is already initialized (since we are calling `libcyclus` from python) the initialization table doesn't really matter, thus our cython modules aren't being imported correctly into the python environment (which I discovered by including a `PyErrPrint()` call after `PyImport_ImportModule()`, I will ensure we have better error checking)

I think this might actually be a really simple fix for cyclus 🤞 I will try to tackle it this weekend
